"""add ci migration test note column

Revision ID: 65b9bcf5df2a
Revises: fd5a5a27db20
Create Date: 2026-07-25 23:51:32.483316
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "65b9bcf5df2a"
down_revision: str | None = "fd5a5a27db20"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_categories",
        sa.Column("ci_migration_test_note", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_categories", "ci_migration_test_note")
    # ### end Alembic commands ###
