"""initial schema

Revision ID: fd5a5a27db20
Revises:
Create Date: 2026-07-25 21:56:27.660187
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd5a5a27db20"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupons",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "discount_type",
            sa.Enum("flat", "percentage", name="coupon_discount_type"),
            nullable=False,
        ),
        sa.Column("discount_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("max_discount_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("min_order_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("max_redemptions_total", sa.Integer(), nullable=True),
        sa.Column("max_redemptions_per_user", sa.SmallInteger(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
    )
    op.create_index(op.f("ix_coupons_code"), "coupons", ["code"], unique=True)
    op.create_table(
        "otp_verifications",
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("hashed_code", sa.String(length=255), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_verifications")),
    )
    op.create_index(
        "ix_otp_phone_purpose", "otp_verifications", ["phone_number", "purpose"], unique=False
    )
    op.create_index(
        op.f("ix_otp_verifications_phone_number"),
        "otp_verifications",
        ["phone_number"],
        unique=False,
    )
    op.create_table(
        "service_categories",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_service_categories_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_service_categories_slug")),
    )
    op.create_table(
        "specializations",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specializations")),
        sa.UniqueConstraint("name", name=op.f("uq_specializations_name")),
    )
    op.create_table(
        "users",
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", "unspecified", name="gender"),
            nullable=False,
        ),
        sa.Column("date_of_birth", sa.DateTime(timezone=True), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "role",
            sa.Enum("patient", "professional", "admin", "ops", name="user_role"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.Enum("active", "suspended", "deleted", name="user_status"), nullable=False
        ),
        sa.Column("referral_code", sa.String(length=12), nullable=False),
        sa.Column("referred_by_id", sa.UUID(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["referred_by_id"], ["users.id"], name=op.f("fk_users_referred_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("referral_code", name=op.f("uq_users_referral_code")),
    )
    op.create_index(op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True)
    op.create_index("ix_users_role_status", "users", ["role", "status"], unique=False)
    op.create_table(
        "addresses",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=30), nullable=False),
        sa.Column("line1", sa.String(length=255), nullable=False),
        sa.Column("line2", sa.String(length=255), nullable=True),
        sa.Column("landmark", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("pincode", sa.String(length=10), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("contact_name", sa.String(length=150), nullable=True),
        sa.Column("contact_phone", sa.String(length=15), nullable=True),
        sa.Column("instructions_for_professional", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_addresses_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_index(
        "ix_addresses_location", "addresses", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_addresses_user_id"), "addresses", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "device_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "platform", sa.Enum("android", "ios", "web", name="device_platform"), nullable=False
        ),
        sa.Column("push_token", sa.String(length=500), nullable=False),
        sa.Column("app_version", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_device_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_tokens")),
    )
    op.create_index(
        "uq_device_tokens_user_token", "device_tokens", ["user_id", "push_token"], unique=True
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("push", "sms", "email", "in_app", name="notification_channel"),
            nullable=False,
        ),
        sa.Column("template_key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("queued", "sent", "failed", name="notification_status"),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "patient_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("known_conditions", postgresql.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("allergies", postgresql.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("current_medications", sa.Text(), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=150), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=15), nullable=True),
        sa.Column("preferred_language", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("date_of_birth", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_patient_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_patient_profiles_user_id")),
    )
    op.create_table(
        "professional_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "professional_type",
            sa.Enum(
                "nurse",
                "physiotherapist",
                "caretaker",
                "lab_technician",
                "doctor",
                "baby_care_specialist",
                name="professional_type",
            ),
            nullable=False,
        ),
        sa.Column("years_of_experience", sa.SmallInteger(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("license_number", sa.String(length=100), nullable=True),
        sa.Column("council_registration_number", sa.String(length=100), nullable=True),
        sa.Column("languages_spoken", postgresql.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("pending", "in_review", "approved", "rejected", name="verification_status"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "availability_status",
            sa.Enum("offline", "online", "on_visit", "break", name="availability_status"),
            nullable=False,
        ),
        sa.Column(
            "current_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("location_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("base_service_radius_km", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("average_rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("total_ratings", sa.Integer(), nullable=False),
        sa.Column("total_visits_completed", sa.Integer(), nullable=False),
        sa.Column("bank_account_number", sa.String(length=50), nullable=True),
        sa.Column("bank_ifsc", sa.String(length=15), nullable=True),
        sa.Column("bank_account_holder_name", sa.String(length=150), nullable=True),
        sa.Column("upi_id", sa.String(length=100), nullable=True),
        sa.Column("is_accepting_bookings", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_professional_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professional_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_professional_profiles_user_id")),
    )
    op.create_index(
        "ix_professional_current_location",
        "professional_profiles",
        ["current_location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "ix_professional_type_status",
        "professional_profiles",
        ["professional_type", "verification_status"],
        unique=False,
    )
    op.create_table(
        "services",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "required_professional_type",
            sa.Enum(
                "nurse",
                "physiotherapist",
                "caretaker",
                "lab_technician",
                "doctor",
                "baby_care_specialist",
                name="professional_type",
            ),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_recurring_eligible", sa.Boolean(), nullable=False),
        sa.Column("requires_prescription", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_categories.id"],
            name=op.f("fk_services_category_id_service_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("slug", name=op.f("uq_services_slug")),
    )
    op.create_table(
        "wallets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wallets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
        sa.UniqueConstraint("user_id", name=op.f("uq_wallets_user_id")),
    )
    op.create_table(
        "care_plans",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("address_id", sa.UUID(), nullable=False),
        sa.Column("total_visits", sa.SmallInteger(), nullable=False),
        sa.Column("visits_per_day", sa.SmallInteger(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("preferred_professional_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_care_plans_address_id_addresses")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["users.id"], name=op.f("fk_care_plans_patient_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["preferred_professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_care_plans_preferred_professional_id_professional_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_care_plans_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_plans")),
    )
    op.create_table(
        "payouts",
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_visits", sa.Integer(), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("commission_deducted", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("adjustments", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "paid", "failed", name="payout_status"),
            nullable=False,
        ),
        sa.Column("provider_reference_id", sa.String(length=100), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_payouts_professional_id_professional_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payouts")),
    )
    op.create_index(
        op.f("ix_payouts_professional_id"), "payouts", ["professional_id"], unique=False
    )
    op.create_table(
        "professional_availability_slots",
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_professional_availability_slots_professional_id_professional_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professional_availability_slots")),
    )
    op.create_index(
        "ix_availability_professional_day",
        "professional_availability_slots",
        ["professional_id", "day_of_week"],
        unique=False,
    )
    op.create_table(
        "professional_documents",
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "government_id",
                "nursing_council_certificate",
                "degree_certificate",
                "police_verification",
                "profile_photo",
                "address_proof",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum("pending", "in_review", "approved", "rejected", name="verification_status"),
            nullable=False,
        ),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_professional_documents_professional_id_professional_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_professional_documents_reviewed_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professional_documents")),
    )
    op.create_table(
        "professional_services",
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("price_override", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_professional_services_professional_id_professional_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_professional_services_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professional_services")),
        sa.UniqueConstraint("professional_id", "service_id", name="uq_professional_service"),
    )
    op.create_table(
        "professional_specializations",
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.UUID(), nullable=False),
        sa.Column("years_of_experience", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_professional_specializations_professional_id_professional_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name=op.f("fk_professional_specializations_specialization_id_specializations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professional_specializations")),
        sa.UniqueConstraint(
            "professional_id", "specialization_id", name="uq_professional_specialization"
        ),
    )
    op.create_table(
        "bookings",
        sa.Column("booking_code", sa.String(length=20), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("professional_id", sa.UUID(), nullable=True),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("address_id", sa.UUID(), nullable=False),
        sa.Column("care_plan_id", sa.UUID(), nullable=True),
        sa.Column(
            "booking_type", sa.Enum("one_time", "care_plan", name="booking_type"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "searching",
                "assigned",
                "confirmed",
                "en_route",
                "in_progress",
                "completed",
                "cancelled",
                "no_show",
                "failed",
                name="booking_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "required_professional_type",
            sa.Enum(
                "nurse",
                "physiotherapist",
                "caretaker",
                "lab_technician",
                "doctor",
                "baby_care_specialist",
                name="professional_type",
            ),
            nullable=False,
        ),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("address_snapshot", sa.Text(), nullable=False),
        sa.Column(
            "service_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("platform_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("professional_payout_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("commission_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("coupon_id", sa.UUID(), nullable=True),
        sa.Column("patient_notes", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("cancelled_by_id", sa.UUID(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_fee_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_bookings_address_id_addresses")
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"], ["users.id"], name=op.f("fk_bookings_cancelled_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["care_plan_id"], ["care_plans.id"], name=op.f("fk_bookings_care_plan_id_care_plans")
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"], ["coupons.id"], name=op.f("fk_bookings_coupon_id_coupons")
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["users.id"], name=op.f("fk_bookings_patient_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_bookings_professional_id_professional_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_bookings_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("booking_code", name=op.f("uq_bookings_booking_code")),
    )
    op.create_index(
        "ix_bookings_patient_status", "bookings", ["patient_id", "status"], unique=False
    )
    op.create_index(
        "ix_bookings_professional_status", "bookings", ["professional_id", "status"], unique=False
    )
    op.create_index("ix_bookings_scheduled_start", "bookings", ["scheduled_start_at"], unique=False)
    op.create_table(
        "booking_offers",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("professional_id", sa.UUID(), nullable=False),
        sa.Column("round_number", sa.SmallInteger(), nullable=False),
        sa.Column("distance_meters", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "rejected", "expired", "cancelled", name="offer_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_offers_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["professional_id"],
            ["professional_profiles.id"],
            name=op.f("fk_booking_offers_professional_id_professional_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_offers")),
    )
    op.create_index(
        "ix_offers_booking_round", "booking_offers", ["booking_id", "round_number"], unique=False
    )
    op.create_index(
        "ix_offers_professional_status",
        "booking_offers",
        ["professional_id", "status"],
        unique=False,
    )
    op.create_table(
        "booking_status_history",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "created",
                "searching",
                "assigned",
                "confirmed",
                "en_route",
                "in_progress",
                "completed",
                "cancelled",
                "no_show",
                "failed",
                name="booking_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "created",
                "searching",
                "assigned",
                "confirmed",
                "en_route",
                "in_progress",
                "completed",
                "cancelled",
                "no_show",
                "failed",
                name="booking_status",
            ),
            nullable=False,
        ),
        sa.Column("changed_by_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_status_history_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["users.id"],
            name=op.f("fk_booking_status_history_changed_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_status_history")),
    )
    op.create_table(
        "booking_visits",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("en_route_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "checked_in_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("checked_in_distance_meters", sa.Integer(), nullable=True),
        sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "checked_out_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("visit_summary_notes", sa.Text(), nullable=True),
        sa.Column("vitals_recorded", sa.Text(), nullable=True),
        sa.Column("proof_of_visit_photo_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_booking_visits_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_visits")),
        sa.UniqueConstraint("booking_id", name=op.f("uq_booking_visits_booking_id")),
    )
    op.create_table(
        "coupon_redemptions",
        sa.Column("coupon_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("discount_applied", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_coupon_redemptions_booking_id_bookings")
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupons.id"],
            name=op.f("fk_coupon_redemptions_coupon_id_coupons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_coupon_redemptions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_redemptions")),
        sa.UniqueConstraint("coupon_id", "booking_id", name="uq_coupon_booking"),
    )
    op.create_table(
        "payments",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_order_id", sa.String(length=100), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=100), nullable=True),
        sa.Column("provider_signature", sa.String(length=255), nullable=True),
        sa.Column(
            "method",
            sa.Enum("upi", "card", "netbanking", "wallet", "cash", name="payment_method"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "authorized",
                "captured",
                "failed",
                "refunded",
                "partially_refunded",
                name="payment_status",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("amount_refunded", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_webhook_payload", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_payments_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["users.id"], name=op.f("fk_payments_patient_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_booking_id"), "payments", ["booking_id"], unique=False)
    op.create_index(
        op.f("ix_payments_provider_order_id"), "payments", ["provider_order_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_provider_payment_id"), "payments", ["provider_payment_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("reviewee_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=50)), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_reviews_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewee_id"], ["users.id"], name=op.f("fk_reviews_reviewee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_reviews_reviewer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("booking_id", "reviewer_id", name="uq_review_booking_reviewer"),
    )
    op.create_table(
        "support_tickets",
        sa.Column("raised_by_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to_id", sa.UUID(), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "urgent", name="support_ticket_priority"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "in_progress", "resolved", "closed", name="support_ticket_status"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"], ["users.id"], name=op.f("fk_support_tickets_assigned_to_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["bookings.id"], name=op.f("fk_support_tickets_booking_id_bookings")
        ),
        sa.ForeignKeyConstraint(
            ["raised_by_id"], ["users.id"], name=op.f("fk_support_tickets_raised_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_tickets")),
    )
    op.create_table(
        "visit_tracking_pings",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column(
            "event",
            sa.Enum("en_route", "checked_in", "checked_out", name="visit_event"),
            nullable=False,
        ),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_visit_tracking_pings_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visit_tracking_pings")),
    )
    op.create_index(
        "ix_tracking_booking_time",
        "visit_tracking_pings",
        ["booking_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("txn_type", sa.Enum("credit", "debit", name="wallet_txn_type"), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "referral_bonus",
                "cancellation_refund",
                "booking_payment",
                "payout",
                "adjustment",
                "promotion",
                name="wallet_txn_reason",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reference_booking_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reference_booking_id"],
            ["bookings.id"],
            name=op.f("fk_wallet_transactions_reference_booking_id_bookings"),
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
            name=op.f("fk_wallet_transactions_wallet_id_wallets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_transactions")),
    )
    op.create_table(
        "support_ticket_messages",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("attachment_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("fk_support_ticket_messages_sender_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["support_tickets.id"],
            name=op.f("fk_support_ticket_messages_ticket_id_support_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_ticket_messages")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_ticket_messages")
    op.drop_table("wallet_transactions")
    op.drop_index("ix_tracking_booking_time", table_name="visit_tracking_pings")
    op.drop_table("visit_tracking_pings")
    op.drop_table("support_tickets")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_payments_provider_payment_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_booking_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("coupon_redemptions")
    op.drop_table("booking_visits")
    op.drop_table("booking_status_history")
    op.drop_index("ix_offers_professional_status", table_name="booking_offers")
    op.drop_index("ix_offers_booking_round", table_name="booking_offers")
    op.drop_table("booking_offers")
    op.drop_index("ix_bookings_scheduled_start", table_name="bookings")
    op.drop_index("ix_bookings_professional_status", table_name="bookings")
    op.drop_index("ix_bookings_patient_status", table_name="bookings")
    op.drop_table("bookings")
    op.drop_table("professional_specializations")
    op.drop_table("professional_services")
    op.drop_table("professional_documents")
    op.drop_index("ix_availability_professional_day", table_name="professional_availability_slots")
    op.drop_table("professional_availability_slots")
    op.drop_index(op.f("ix_payouts_professional_id"), table_name="payouts")
    op.drop_table("payouts")
    op.drop_table("care_plans")
    op.drop_table("wallets")
    op.drop_table("services")
    op.drop_index("ix_professional_type_status", table_name="professional_profiles")
    op.drop_index(
        "ix_professional_current_location",
        table_name="professional_profiles",
        postgresql_using="gist",
    )
    op.drop_table("professional_profiles")
    op.drop_table("patient_profiles")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("uq_device_tokens_user_token", table_name="device_tokens")
    op.drop_table("device_tokens")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_addresses_user_id"), table_name="addresses")
    op.drop_index("ix_addresses_location", table_name="addresses", postgresql_using="gist")
    op.drop_table("addresses")
    op.drop_index("ix_users_role_status", table_name="users")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_table("users")
    op.drop_table("specializations")
    op.drop_table("service_categories")
    op.drop_index(op.f("ix_otp_verifications_phone_number"), table_name="otp_verifications")
    op.drop_index("ix_otp_phone_purpose", table_name="otp_verifications")
    op.drop_table("otp_verifications")
    op.drop_index(op.f("ix_coupons_code"), table_name="coupons")
    op.drop_table("coupons")
    # ### end Alembic commands ###
